### ISSUE TITLE
there is no package called ‘BiocParallel’

### ISSUE THREAD

**Issue by rlittman16** [Bioconductor/copy-number-analysis#4]
When I try to start cn.mops with library(cn.mops) I get this error 

Error: package or namespace load failed for ‘cn.mops’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘BiocParallel’

R version 3.4.1
Bioconductor version 3.6 (BiocInstaller 1.28.0)

Thanks in advanced

**Comment by mtmorgan** [comment]
Try installing BiocParallel
```
source("https://bioconductor.org./biocLite.R")
biocLite("BiocParallel")
```
