### ISSUE TITLE
singlecn.mops

### ISSUE THREAD

**Issue by fre335** [Bioconductor/copy-number-analysis#5]
Hello,

I am using cnMOPS for Exome cnv analyse which is working fine, since i have multiple samples.
However i want to use the function singlecn.mops to detect cnvs in WGS data, where i only have one sample. Unfortunatly i get an Error message:

Starting segmentation algorithm...
Using "fastseg" for segmentation.
Error in checkForRemoteErrors(val) : 
  one node produced an error:  missing value, where TRUE/FALSE needed.
In addition: Warning messages:
1: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 1 out-of-bound range located on sequence chrMT. Note that ranges located on a sequence
  whose length is unknown (NA) or on a circular sequence are not considered out-of-bound (use seqlengths() and
  isCircular() to get the lengths and circularity flags of the underlying sequences). You can use trim() to trim
  these ranges. See ?`trim,GenomicRanges-method` for more information.
2: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 1 out-of-bound range located on sequence chrMT. Note that ranges located on a sequence
  whose length is unknown (NA) or on a circular sequence are not considered out-of-bound (use seqlengths() and
  isCircular() to get the lengths and circularity flags of the underlying sequences). You can use trim() to trim
  these ranges. See ?`trim,GenomicRanges-method` for more information.

My code looks like this:
#######

library(cn.mops)

bams = "*******.bam"

bam_counts = getReadCountsFromBAM(bams, parallel=2) 

res = singlecn.mops(bam_counts, parallel=2) 

final_genome_cnv = calcIntegerCopyNumbers(res)

#######

Do you have any suggestions what i am doing wrong?
Thanks in Advance!

**Comment by lshep** [comment]
Questions about usage and encountered ERRORs are better asked on the support site. While opening github issues are better for reporting bugs in the code. Could you please post this on the [Support Site](https://support.bioconductor.org/) along with your `sessionInfo()`
