### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by deepalivasoya** [Bioconductor/copy-number-analysis#7]
Hello, 

I am trying to simply install the cp.mops. I tried in different R version - 3.2.1, 3.4.1, 3.6.1. It doesn't support any of it? What R version can I use to install it? 

Thank you.

**Comment by lshep** [comment]
Please show the command you are trying to install ?  In the above I'll assume  `cn.mos` was a typo for `cn.mops`?
For R 3.6.1 
```
install.packages("BiocManager")
BiocManager::install("cn.mops")
```

**Comment by lshep** [comment]
If that fails please show the command and the complete output given in your R terminal

**Comment by deepalivasoya** [comment]
Oh yes its "cn.mops". I just corrected it. Thank you for noticing it. 
I am doing it direct install by install.packages. 
install.packages("cn.mops")

**Comment by deepalivasoya** [comment]
> Please show the command you are trying to install ? In the above I'll assume `cn.mos` was a typo for `cn.mops`?
> For R 3.6.1
> 
> ```
> install.packages("BiocManager")
> BiocManager::install("cn.mops")
> ```

**Comment by deepalivasoya** [comment]
Thank you Isep. It worked with R3.5.3.

**Comment by LiNk-NY** [comment]
We would recommend that you use `BiocManager` for R versions greater than `3.5.0`. 
```r
BiocManager::install("cn.mops")
```
Otherwise, refer to the appropriate release for installation instructions https://bioconductor.org/about/release-announcements/
