### ISSUE TITLE
Error in if (WL >= sl[i]) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by deb0612** [Bioconductor/copy-number-analysis#8]
Dear sir,
I am using cn.mops in my WES data with hg38 reference sequence(Homo_sapiens_assembly38.fasta).
When I use bamDataRanges <- getReadCountsFromBAM(BAMFiles) command.It shows:
**Error in if (WL >= sl[i]) { : missing value where TRUE/FALSE needed**
How is that?

**Comment by lshep** [comment]
Hello @deb0612   You might have more success posting your question on the [bioconductor support site](https://support.bioconductor.org/) .  When you post there you will need to provide more information for anyone to be able to help you.  Like the structure of BamFiles and your `sessionInfo()`
